### ISSUE TITLE
Crashing frequently - typo as probable cause

### ISSUE THREAD

**Issue by cyberponk** [poliva/pyqtggpo#26]
At line 191 of ggpofba.py, I think the socket.errror was typed in wrong, it has 3 'r'
shouldn´t it be socket.error instead?

Anyway, my fightcade is closing frequently, during chat or game time. It simply closes. 
If i´m in a game, the game window stays open with freezed image and sound.
Sometimes happens after 10 seconds, sometimes after 10 minutes, very random, but always happens.

This is the log:

Traceback (most recent call last):
  File "<string>", line 400, in <module>
  File "<string>", line 364, in main
  File "<string>", line 191, in udp_proxy
AttributeError: 'module' object has no attribute 'errror'

**Comment by poliva** [comment]
Hi, fixed the error in git, but I highly doubt this is the cause of your crashes/freezes during game.
Let me know your fightcade username and I can check the server logs.

**Comment by cyberponk** [comment]
my username is cyberponk

How do I download the fixed version? I have no idea how to compile that
code :(

*Turboroe*
*Marcos Roehe*
*Fone: *(51) 9104-5756

2015-05-06 3:02 GMT-03:00 Pau Oliva <notifications@github.com>:

**Comment by poliva** [comment]
Don't worry about the fixed version it won't help you. 25 out of your last 28 games closed on your end, it looks like your internet connection disconnects established connections every once in a while:
<pre>
2015-04-30 04:48:43,629:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-7338-1430368403.85)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-04-30 05:03:47,791:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-7351-1430369347.38)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 00:12:51,295:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-8124-1430525104.46)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 00:52:48,494:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-5816-1430527614.18)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 01:00:57,044:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-7998-1430528082.51)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 01:12:26,159:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1730-1430528940.26)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 20:39:53,974:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1268-1430598826.19)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 20:59:53,085:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-2347-1430599952.10)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 21:08:30,003:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-4213-1430600469.79)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-02 21:19:51,184:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-2335-1430601161.55)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 21:44:35,193:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1533-1430775830.40)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 21:54:30,746:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1504-1430775945.20)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:04:29,241:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1875-1430776715.16)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:14:28,559:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-6648-1430777136.47)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:24:28,590:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-2643-1430777716.22)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:34:28,253:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-5074-1430778286.26)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:43:52,001:INFO:[cyberponk@201.xx.xx.xx:6006#kof2002/player(challenge-2098-1430778892.38)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-04 22:54:28,249:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-4819-1430779487.58)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 04:24:29,455:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-7886-1430799407.83)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 04:34:29,814:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1248-1430799889.10)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 04:44:29,679:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-9987-1430800519.43)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 04:54:29,084:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-7546-1430801630.39)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 05:03:48,827:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-2477-1430801682.75)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 22:32:31,622:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-1978-1430864608.53)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
2015-05-05 22:52:31,329:INFO:[cyberponk@201.xx.xx.xx:6004#kof2002/player(challenge-5252-1430866182.49)] Can't read data. Finishing. ERROR: error(104, 'Connection reset by peer')
</pre>

Make sure to play using ethernet cable (not wifi), and if you already are playing with cable, then call your ISP to have your internet line fixed.

**Comment by cyberponk** [comment]
Ok, i noticed my connection is unstable lately. Thanks.

*Turboroe*
*Marcos Roehe*
*Fone: *(51) 9104-5756

2015-05-06 4:06 GMT-03:00 Pau Oliva <notifications@github.com>:

**Comment by cyberponk** [comment]
Poliva, my ISP fixed my connection (browing perfectly now) but fightcade still crashes once in a while :(
can you send me the latest compiled version to check if it may be fixed?

thanks.
