### ISSUE TITLE
FinalBurn Alpha client fails to run from Fightcade

### ISSUE THREAD

**Issue by petran79** [poliva/pyqtggpo#33]
I am using Ubuntu 15.04 64-bit
Wine 1.7 is installed
linux-install.sh list all files present

For Final Burn Emulator:
ggpofba.py runs with command "python ggpofba.py"
It also runs with command "./ggpofba.sh"
I configure ROM settings, controllers, display and sound fine in the FBA emulator.
Games run without issues.

Regarding Fightcade client:
for main.py I have to enter "sudo python main.py"
Or else without "sudo" it gives me the message:

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    sys.exit(main(sys.argv))
  File "main.py", line 39, in main
    controller = Controller()
  File "/home/petros/.wine/drive_c/FightCade/ggpo/common/controller.py", line 93, in __init__
    self.sigStatusMessage.connect(logdebug().info)
  File "/home/petros/.wine/drive_c/FightCade/ggpo/common/util.py", line 86, in logdebug
    loggerInit()
  File "/home/petros/.wine/drive_c/FightCade/ggpo/common/util.py", line 102, in loggerInit
    os.path.join(expanduser("~"), 'fightcade-debug.log'), mode='a', maxBytes=500000, backupCount=10)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/petros/fightcade-debug.log'

the fightcade-debug log has the following:
'ascii' codec can't decode byte 0xce in position 13: ordinal not in range(128)

When I log to the Fightcade main GUI it locates the ROMs folder fine. They appear linked in the ROMs folder. 

Problem is when I click the Eye icon to watch a match, nothing happens. No FBA client appears. So I can not challenge players either.

Is there something I am missing? Permissions or files?

**Comment by poliva** [comment]
First run this:
`sudo rm -rf ~/fightcade* ~/ggpo*.ini /home/petros/fightcade* /home/petros/ggpo*.ini`

Then start fightcade as regular user, **without sudo**.
